title               : "dukecroc"
tagline             : "A personal blog."
description         : "This is a personal blog by Croc."
url                 : "http://dukecroc.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl             : "" # the subpath of your site, e.g. /blog
email               : dukecroc@gmail.com
lang                : zh-Hant-TW

author:
  name              : dukecroc
  twitter           : dukecroc

show_excerpts       : true
disable_disk_cache  : true # Disable caching of content to disk in order to skip creating a .jekyll-cache or similar directory at the source to avoid interference with virtual environments and third-party directory watchers. Caching to disk is always disabled in safe mode.
ignore_theme_config : true # Jekyll 4.0 started allowing themes to bundle a _config.yml to simplify theme-onboarding for new users. In the unfortunate situation that importing a bundled theme configuration messes up the merged site-configuration, the user can configure Jekyll to not import the theme-config entirely.




# [Default Configuration]
# Jekyll runs with the following configuration options by default. 
# Alternative settings for these options can be explicitly specified 
# in the configuration file or on the command-line.
# -------------------------
# Where things are
source              : .
destination         : ./_build # default: ./_site
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  tag:
    output          : true
  posts:
    output          : true


# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : 
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Gemfile.lock
  - jekyll_blog.code-workspace
  - jekyll_blog.sublime-projec
  - jekyll_blog.sublime-workspace
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : 
  - jekyll-paginate
  - jekyll-feed

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : <!--more-->  # default: "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate            : 10
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
rdiscount:
  extensions        : []

redcarpet:
  extensions        : []

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false




# [Front Matter Defaults]
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       # type: "posts" # previously `post` in Jekyll 2.2.
#     values:
#       layout: "page"
