title               : dukecroc
tagline             : A personal blog.
description         : This is a personal blog by Croc.
url                 : https://dukecroc.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl             : "" # the subpath of your site, e.g. "/blog" with be => http://example.com/blog
lang                : zh-Hant-TW

## Social Links
contacts:
  email             : dukecroc@gmail.com
  facebook          : ""
  twitter           : dukecroc
  instagram         : dukecroc

show_excerpts       : true

# Disable caching of content to disk in order to skip creating a .jekyll-cache or similar directory at the source to avoid interference with virtual environments and third-party directory watchers. Caching to disk is always disabled in safe mode.
disable_disk_cache  : true

# Jekyll 4.0 started allowing themes to bundle a _config.yml to simplify theme-onboarding for new users. In the unfortunate situation that importing a bundled theme configuration messes up the merged site-configuration, the user can configure Jekyll to not import the theme-config entirely.
ignore_theme_config : true




## [Default Configuration]
## Jekyll runs with the following configuration options by default. 
## Alternative settings for these options can be explicitly specified 
## in the configuration file or on the command-line.
## -------------------------

## Where things are
# source              : .
destination         : ./_build # default: ./_site
# plugins_dir         : _plugins
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# sass:
  # sass_dir: _sass
collections:
  # posts:
  #   output          : true
  category: # This allows you to use the collection throughout your templates
    output          : true # This allows us to generate pages for each category where we can list all posts under that category. 


## Handling Reading
# safe                : false
# include             : [".htaccess"]
exclude             : 
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Gemfile.lock
  - .code-workspace
  - .sublime-projec
  - .sublime-workspace
# keep_files          : [".git", ".svn"]
# encoding            : "utf-8"
# markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
# strict_front_matter : false

## Filtering Content
# show_drafts         : null
# limit_posts         : 0
# future              : false
# unpublished         : false

## Plugins
# whitelist           : []
plugins             : 
  - jekyll-paginate
  - jekyll-feed

## Conversion
# markdown            : kramdown
# highlighter         : rouge
# lsi                 : false
excerpt_separator   : <!--more-->  # default: "\n\n"
# incremental         : false

## Serving
# detach              : false
# port                : 4000
# host                : 127.0.0.1
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

## Outputting
permalink           :  "/:categories/:title" # default: "date"
paginate            : 5
# paginate_path       : /page:num
# timezone            : null

# quiet               : false
# verbose             : false
# defaults            : []

# liquid:
  # error_mode        : warn
  # strict_filters    : false
  # strict_variables  : false

# Markdown Processors
# rdiscount:
  # extensions        : []

# redcarpet:
  # extensions        : []

# kramdown:
  # auto_ids          : true
  # entity_output     : as_char
  # toc_levels        : [1, 2, 3, 4, 5, 6]
  # smart_quotes      : lsquo,rsquo,ldquo,rdquo
  # input             : GFM
  # hard_wrap         : false
  # footnote_nr       : 1
  # show_warnings     : false




## Front Matter Defaults Setting Example
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       # type: "posts" # previously `post` in Jekyll 2.2.
#     values:
#       layout: "page"

defaults:
  - # For our convenience, we’ll add a default layout property to each category.
    scope:
      path          : ""
      type          : category
    values:
      layout        : "category" # This sets the default layout to category for all elements of our category collection.
